= REST

== Representational state transfer

* Mode de communication client-serveur sur HTTP
* Taillé pour de la communication Machine-To-Machine
* Ensemble de règle et de pratiques qui ont pour but de standardiser les échanges
* Indépendances vis-à-vis de quelconque langage d'implémentation sous-jacent

== Representational state transfer

* Plus léger que le protocole SOAP, il s'est imposé comme un des standards actuels
* D'autres protocoles de communication Machine-To-Machine existent
  - gRPC
* Pas de conservation de l'état entre deux requêtes

== HTTP(S)

* Protocole de communication de niveau applicatif (Niveau 7) se basant sur la couche de transport TCP (Niveau 4)
* Port 80 : HTTP
* Port 443 : HTTPS
* Le client utilise des commmandes (ou méthodes ou verbes) prédéfinies dans le protocole pour échanger avec le serveur

== Requête HTTP
:plantuml-server-url: http://www.plantuml.com/plantuml
[plantuml,http-request-response]
----
Client -> Serveur: HTTP Request
Client <- Serveur: HTTP Response
----

== Anatomie d'une requête HTTP

|=== 

| Commande | GET / HTTP/1.1  

| Request headers | Host: example.com

| Body (Optionnel) | Ce qu'on veut envoyer au serveur

|=== 

== Requête HTTP

:source-highlighter: highlightjs
:source-language: bash

[source]
----
$ telnet example.com 80
Trying 2606:2800:220:1:248:1893:25c8:1946...
Connected to example.com.
Escape character is '^]'.
GET / HTTP/1.1
Host: example.com
----


== Anatomie d'une réponse HTTP

== La philosophie de REST

* Exposer des ressources (entités ?) sur des URLs immutables accessibles selon une ou plusieurs méthodes

== Les verbes

* Les verbes donnent une sémantique à la requête
* Il y en a 9 au total
* 4 "principaux" sont les plus utilisés
  - GET
  - POST
  - PUT
  - DELETE

== GET

* Utilisé pour de la consultation des ressources
* Permet de récupérer une entité simple ou une liste d'entités
* Une requête GET n'a pas de body
* Les informations sont envoyées soit par 
  - des "path params" : composants du chemin qui seront récupérés par le parsing de ce dernier
  - des "query params" : liste de paires clé/valeur se trouvant dans l'url aprs le "?"

== GET (quelques exemples)

* La liste des étudiants de l'université

[source]
----
GET https://monserveur.com/etudiants
----

* La liste des étudiants du M1 Informatique

[source]
----
GET https://monserveur.com/etudiants?promo=M1INFO
----

* L'étudiant dont le numéro est est 254633

[source]
----
GET https://monserveur.com/etudiants/254633
----

== POST

* Intention d'ajouter une nouvelle ressource dans le système
* Les informations permettant de créer la ressource se trouvent dans le body de la requête
* Les "path params" et "query params" seront envoyés mais il doit y avoir une sémantique qui se justifie
* La réponse à la requête peut contenir le résultat de la création par l'application
* Le format du body doit être précisé en tant que header pour que l'application puisse correctement désérialiser les données envoyées 

== POST (exemple)

[source]
----
POST https://monserveur.com/etudiants
----

* Request Body

:source-highlighter: highlightjs
:source-language: json

[source]
----
{
    "nom": "John",
    "prenom": "Doe",
}
----

* Response Body

[source]
----
{
    "id": 1895, 
    "nom": "John",
    "prenom": "Doe",
    "villeDeNaissance": "Non Précisée"
}
----

== PUT

* Intention de modifier une ressource existante
* L'identification de la ressource à modifier est en général contenue dans l'URL
* Le body de la requête contient les champs modifiés de la ressource
* La réponse à la requête peut contenir le résultat de la modification de la ressource par l'application

== PUT (exemple)

[source]
----
PUT https://monserveur.com/etudiants/1895
----

* Request Body

:source-highlighter: highlightjs
:source-language: json

[source]
----
{
    "nom": "John",
    "prenom": "Doe",
    "villeDeNaissance": "New York"
}
----

* Response Body

[source]
----
{
    "id": 1895, 
    "nom": "John",
    "prenom": "Doe",
    "villeDeNaissance": "New York"
}
----

== DELETE

* Intention de supprimer une ressource
* La requête n'a pas de body
* La réponse n'a pas de body non plus
* L'identification de la ressource à supprimer est obligatoirement contenue dans l'URL

== DELETE (exemple)

[source]
----
DELETE https://monserveur.com/etudiants/1895
----

== Les codes de statut

* Les codes sont des indications sur les résultats des traitements réalisés par le serveur
* Les codes de statut sont standardisés 
  - Il est fortement déconseillé d'utiliser des codes de statuts personnalisés

https://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml

== Les codes de statut (2XX)

* Codes de retour utilisés en cas de succès
* La requête a pu être traitée sans erreur
* Les plus connus
  - 200 OK: le plus neutre 
  - 201 CREATED: utile lors de la création d'une ressource en POST
  - 204 NO CONTENT : utile en POST ou PUT si le serveur ne renvoie rien dans le body

== Les codes de statut (3XX)

* Indiquent en général une redirection qui peut-être permanente ou temporaire
* La réponse contient un header "Location" qui précise la nouvelle URL de la ressource
* Les plus connus
  - 300 Multiple Choices: la requête ne précisaient pas le format de réponse souhaité
  - 307 Temporary Redirect : le client devrait aller voir ailleurs mais quand repasser par là la prochaine fois

== Les codes de statut (4XX)

* Indiquent une erreur lors du traitement de la requête par l'application
  - il s'agit plus d'une erreur "métier"
* Les plus connus
  - 400 Bad Request : le client a envoyé une requête incomplète ou au mauvais format  
  - 403 Forbidden : le client n'a pas les droits pour accéder à la ressource
  - 404 Not Found : la ressource demandée n'existe pas ou plus

== Les codes de statut (5XX)

* Indiquent une erreur technique qui n'est pas dans le fonctionnement standard de l'application
* Les plus connus
  - 500 Internal Server Error : peut être levé par une exception non catchée coté serveur
  - 503 Service Unavailable : erreur potentiellement temporaire (surcharge par exemple)

== Les principaux types de headers

== Les mediatypes

== HATEOAS

== La documentation des APIS


